const TAROT_CARDS = [
    { id: 0, name: "愚者", en: "The Fool", numeral: "0", img: "ar00.jpg", keywords: ["新开始", "冒险", "天真", "自由"], upright: "新的旅程即将开始，保持开放和乐观的心态。勇敢地踏出第一步，相信宇宙的指引。", reversed: "鲁莽行事可能导致风险。需要更多谨慎和规划，避免天真的决定。" },
    { id: 1, name: "魔术师", en: "The Magician", numeral: "I", img: "ar01.jpg", keywords: ["创造力", "技能", "意志力", "掌控"], upright: "你拥有实现目标所需的所有资源和能力。专注你的意志，将想法转化为现实。", reversed: "才能被浪费或误用。可能缺乏方向或自信，需要重新聚焦。" },
    { id: 2, name: "女祭司", en: "The High Priestess", numeral: "II", img: "ar02.jpg", keywords: ["直觉", "神秘", "潜意识", "智慧"], upright: "倾听内心的声音和直觉。答案就在你的潜意识中，静心倾听神圣的智慧。", reversed: "忽视直觉或内心声音。可能信息被隐藏，需要更深入地探索。" },
    { id: 3, name: "皇后", en: "The Empress", numeral: "III", img: "ar03.jpg", keywords: ["丰饶", "母性", "创造", "自然"], upright: "创造力和丰饶的能量环绕着你。这是滋养、成长和manifesting的时期。", reversed: "创造受阻或缺乏关怀。可能过度依赖他人，需要自我关爱。" },
    { id: 4, name: "皇帝", en: "The Emperor", numeral: "IV", img: "ar04.jpg", keywords: ["权威", "结构", "控制", "父亲"], upright: "建立秩序和结构。发挥领导力，承担责任，为未来建立稳固的基础。", reversed: "专制或缺乏控制。可能过度严苛或完全失控，寻找平衡。" },
    { id: 5, name: "教皇", en: "The Hierophant", numeral: "V", img: "ar05.jpg", keywords: ["传统", "信仰", "教导", " conformity"], upright: "遵循传统和精神教导。寻求指导，学习古老智慧，尊重既定体系。", reversed: "打破传统或叛逆。可能需要建立自己的信念体系。" },
    { id: 6, name: "恋人", en: "The Lovers", numeral: "VI", img: "ar06.jpg", keywords: ["爱情", "选择", "和谐", "价值观"], upright: "重要的选择摆在面前。在爱情或价值观层面做出决定，追求和谐与真实。", reversed: "不和谐或错误的选择。可能面临价值观冲突或关系危机。" },
    { id: 7, name: "战车", en: "The Chariot", numeral: "VII", img: "ar07.jpg", keywords: ["意志", "胜利", "决心", "控制"], upright: "强大的意志力带来胜利。集中精力，克服障碍，朝着目标坚定前进。", reversed: "失控或缺乏方向。可能遇到阻碍，需要重新评估策略。" },
    { id: 8, name: "力量", en: "Strength", numeral: "VIII", img: "ar08.jpg", keywords: ["勇气", "耐心", "内在力量", "慈悲"], upright: "内在的力量和勇气。以温柔和耐心面对挑战，真正的力量来自内心。", reversed: "自我怀疑或软弱。可能缺乏自信或过度强硬，寻找平衡。" },
    { id: 9, name: "隐士", en: "The Hermit", numeral: "IX", img: "ar09.jpg", keywords: ["内省", "孤独", "指引", "智慧"], upright: "独处和内省的时刻。寻求内在的智慧，远离喧嚣，照亮真理的道路。", reversed: "孤立或退缩。可能过度封闭，需要适度社交。" },
    { id: 10, name: "命运之轮", en: "Wheel of Fortune", numeral: "X", img: "ar10.jpg", keywords: ["命运", "转变", "循环", "机遇"], upright: "命运的轮转带来新的机遇。生命周期的转变，拥抱变化和好运。", reversed: "抗拒变化或厄运。可能需要接受生命的循环本质。" },
    { id: 11, name: "正义", en: "Justice", numeral: "XI", img: "ar11.jpg", keywords: ["公正", "真理", "因果", "法律"], upright: "公正和真理的显现。因果报应，做出公正的决定，承担责任。", reversed: "不公正或逃避责任。可能面临偏见或需要重新审视事实。" },
    { id: 12, name: "倒吊人", en: "The Hanged Man", numeral: "XII", img: "ar12.jpg", keywords: ["牺牲", "等待", "新视角", "放下"], upright: "暂停和等待的时机。换个角度看问题，通过牺牲获得更高的洞见。", reversed: "拖延或无意义的牺牲。可能需要采取行动而非等待。" },
    { id: 13, name: "死神", en: "Death", numeral: "XIII", img: "ar13.jpg", keywords: ["结束", "转变", "重生", "放下"], upright: "一个周期的结束和新的开始。拥抱转变，放下旧的，迎接新生。", reversed: "抗拒改变或停滞不前。恐惧转变，需要接受结束。" },
    { id: 14, name: "节制", en: "Temperance", numeral: "XIV", img: "ar14.jpg", keywords: ["平衡", "调和", "耐心", "中庸"], upright: "平衡与调和。找到中间道路，融合对立面，保持耐心和和谐。", reversed: "失衡或过度。可能极端化或缺乏长期愿景。" },
    { id: 15, name: "恶魔", en: "The Devil", numeral: "XV", img: "ar15.jpg", keywords: ["束缚", "物质", "诱惑", "阴影"], upright: "物质世界的束缚。认识到限制和依赖，面对阴影自我。", reversed: "解放或打破束缚。可能获得自由或继续沉溺。" },
    { id: 16, name: "塔", en: "The Tower", numeral: "XVI", img: "ar16.jpg", keywords: ["突变", "灾难", "觉醒", "毁灭"], upright: "突然的改变和觉醒。旧结构的崩塌为新生腾出空间。", reversed: "避免灾难或延迟改变。可能恐惧转变或内心崩溃。" },
    { id: 17, name: "星星", en: "The Star", numeral: "XVII", img: "ar17.jpg", keywords: ["希望", "灵感", "宁静", "治愈"], upright: "希望和灵感的光芒。经历风暴后的平静，宇宙的治愈和祝福。", reversed: "失去希望或绝望。可能需要重新连接精神愿景。" },
    { id: 18, name: "月亮", en: "The Moon", numeral: "XVIII", img: "ar18.jpg", keywords: ["幻象", "直觉", "恐惧", "潜意识"], upright: "迷雾中的指引。相信直觉，探索潜意识的深层真相。", reversed: "释放恐惧或清晰。可能走出困惑或继续迷茫。" },
    { id: 19, name: "太阳", en: "The Sun", numeral: "XIX", img: "ar19.jpg", keywords: ["快乐", "成功", "活力", "光明"], upright: "光明和成功的时刻。乐观，活力四射，万物欣欣向荣。", reversed: "暂时阴霾或过度乐观。可能需要寻找内在的光明。" },
    { id: 20, name: "审判", en: "Judgement", numeral: "XX", img: "ar20.jpg", keywords: ["觉醒", "重生", "召唤", "决定"], upright: "觉醒和重生的召唤。听取宇宙的呼唤，做出重要的生命决定。", reversed: "自我怀疑或拒绝召唤。可能逃避改变或过度批判。" },
    { id: 21, name: "世界", en: "The World", numeral: "XXI", img: "ar21.jpg", keywords: ["完成", "整合", "成就", "旅程"], upright: "周期的圆满完成。达成目标，整合所有经验，准备新的旅程。", reversed: "未完成或延迟。可能需要最后的努力来完成循环。" },
    { id: 22, name: "权杖王牌", en: "Ace of Wands", numeral: "A", img: "wa01.jpg", keywords: ["灵感", "新开始", "潜力"], upright: "新的灵感火花。创造力的爆发，新事业或激情项目的开始。", reversed: "延迟或缺乏方向。创意受阻，需要更多明确性。" },
    { id: 23, name: "权杖二", en: "Two of Wands", numeral: "2", img: "wa02.jpg", keywords: ["计划", "决定", "进展"], upright: "计划的阶段。站在门槛上，展望未来，做出战略决定。", reversed: "恐惧或保守。可能害怕未知，需要大胆前行。" },
    { id: 24, name: "权杖三", en: "Three of Wands", numeral: "3", img: "wa03.jpg", keywords: ["扩展", "远见", "机遇"], upright: "扩展的视野。计划开始成形，看到更广阔的可能。", reversed: "障碍或缺乏远见。可能需要调整期望。" },
    { id: 25, name: "权杖四", en: "Four of Wands", numeral: "4", img: "wa04.jpg", keywords: ["庆祝", "和谐", "家"], upright: "庆祝和和谐。达成里程碑，家庭幸福，享受成果。", reversed: "过渡或缺乏支持。可能需要加强基础。" },
    { id: 26, name: "权杖五", en: "Five of Wands", numeral: "5", img: "wa05.jpg", keywords: ["冲突", "竞争", "张力"], upright: "冲突和竞争。不同的观点碰撞，需要找到建设性的解决方式。", reversed: "避免冲突或内部压力。可能需要寻求和谐。" },
    { id: 27, name: "权杖六", en: "Six of Wands", numeral: "6", img: "wa06.jpg", keywords: ["胜利", "荣誉", "认可"], upright: "胜利和公开认可。成功达成目标，获得荣誉和赞赏。", reversed: "自负或缺乏认可。可能需要谦逊或重新评估。" },
    { id: 28, name: "权杖七", en: "Seven of Wands", numeral: "7", img: "wa07.jpg", keywords: ["防御", "坚持", "挑战"], upright: "坚守立场。为信念而战，保持优势，迎接挑战。", reversed: "放弃或不堪重负。可能需要选择战斗。" },
    { id: 29, name: "权杖八", en: "Eight of Wands", numeral: "8", img: "wa08.jpg", keywords: ["快速", "行动", "进展"], upright: "快速的行动。事情迅速发展，抓住机遇，向前冲刺。", reversed: "延迟或等待。可能需要耐心或调整计划。" },
    { id: 30, name: "权杖九", en: "Nine of Wands", numeral: "9", img: "wa09.jpg", keywords: ["韧性", "坚持", "防御"], upright: "坚持和韧性。经历考验但依然站立，最后一搏的力量。", reversed: "疲惫或放弃。可能需要休息和恢复。" },
    { id: 31, name: "权杖十", en: "Ten of Wands", numeral: "10", img: "wa10.jpg", keywords: ["负担", "责任", "辛苦"], upright: "沉重的负担。责任过多，需要重新分配或放下一些。", reversed: "释放或委托。可能需要寻求帮助。" },
    { id: 32, name: "权杖侍从", en: "Page of Wands", numeral: "P", img: "wapa.jpg", keywords: ["探索", "热情", "发现"], upright: "热情的探索者。新的兴趣，充满好奇心，踏上发现之旅。", reversed: "缺乏方向或延迟。可能需要更多专注。" },
    { id: 33, name: "权杖骑士", en: "Knight of Wands", numeral: "K", img: "wakn.jpg", keywords: ["行动", "冒险", "冲动"], upright: "充满活力的行动。追求激情，冒险前进，能量充沛。", reversed: "鲁莽或延迟。可能需要更多计划。" },
    { id: 34, name: "权杖王后", en: "Queen of Wands", numeral: "Q", img: "waqu.jpg", keywords: ["自信", "创造力", "独立"], upright: "自信和创造力。充满热情，独立坚强，鼓舞他人。", reversed: "自我怀疑或嫉妒。可能需要重建自信。" },
    { id: 35, name: "权杖国王", en: "King of Wands", numeral: "K", img: "waki.jpg", keywords: ["领导", "愿景", "企业家"], upright: "有远见的领导者。鼓舞人心，采取行动，实现愿景。", reversed: "专制或冲动。可能需要更多考虑他人。" },
    { id: 36, name: "圣杯王牌", en: "Ace of Cups", numeral: "A", img: "cu01.jpg", keywords: ["爱", "新关系", "情感"], upright: "新的情感开始。爱情的萌芽，情感满足，心灵敞开。", reversed: "情感阻滞或空虚。可能需要自我关爱。" },
    { id: 37, name: "圣杯二", en: "Two of Cups", numeral: "2", img: "cu02.jpg", keywords: ["伙伴", "连接", "统一"], upright: "和谐的伙伴关系。深刻的连接，互相理解，团结一致。", reversed: "分离或不和谐。可能需要重新评估关系。" },
    { id: 38, name: "圣杯三", en: "Three of Cups", numeral: "3", img: "cu03.jpg", keywords: ["庆祝", "友谊", "团体"], upright: "庆祝和友谊。与朋友欢聚，分享喜悦，社交快乐。", reversed: "过度社交或孤立。可能需要平衡社交和独处。" },
    { id: 39, name: "圣杯四", en: "Four of Cups", numeral: "4", img: "cu04.jpg", keywords: ["冷漠", "冥想", "不满"], upright: "沉思和不满。对现状厌倦，需要新的情感刺激。", reversed: "觉醒或新机遇。可能需要睁开眼睛看机会。" },
    { id: 40, name: "圣杯五", en: "Five of Cups", numeral: "5", img: "cu05.jpg", keywords: ["失落", "悲伤", "遗憾"], upright: "悲伤和失落。关注失去，但也别忘了还拥有的。", reversed: "接受或前进。可能需要走出悲伤。" },
    { id: 41, name: "圣杯六", en: "Six of Cups", numeral: "6", img: "cu06.jpg", keywords: ["怀旧", "童年", "纯真"], upright: "怀旧和纯真。回忆美好时光，童年联系，简单快乐。", reversed: "活在过去或天真。可能需要面向未来。" },
    { id: 42, name: "圣杯七", en: "Seven of Cups", numeral: "7", img: "cu07.jpg", keywords: ["幻想", "选择", "幻象"], upright: "多种选择和幻想。梦想丰富，但需分辨现实与幻想。", reversed: "清晰或专注。可能需要做出明确选择。" },
    { id: 43, name: "圣杯八", en: "Eight of Cups", numeral: "8", img: "cu08.jpg", keywords: ["离开", "寻找", "失望"], upright: "离开和寻找。放下不再满足的，寻求更深的意义。", reversed: "停留或恐惧改变。可能需要勇气前行。" },
    { id: 44, name: "圣杯九", en: "Nine of Cups", numeral: "9", img: "cu09.jpg", keywords: ["满足", "愿望", "幸福"], upright: "情感满足。愿望成真，内心快乐，享受成果。", reversed: "不满足或贪婪。可能需要重新定义幸福。" },
    { id: 45, name: "圣杯十", en: "Ten of Cups", numeral: "10", img: "cu10.jpg", keywords: ["家庭", "和谐", "圆满"], upright: "家庭幸福和情感圆满。深层满足，关系和谐，美好生活。", reversed: "家庭问题或不和谐。可能需要解决内部冲突。" },
    { id: 46, name: "圣杯侍从", en: "Page of Cups", numeral: "P", img: "cupa.jpg", keywords: ["敏感", "消息", "创意"], upright: "敏感和创意的消息。情感直觉，艺术表达，温柔的心灵。", reversed: "情绪化或创意阻滞。可能需要更多务实。" },
    { id: 47, name: "圣杯骑士", en: "Knight of Cups", numeral: "K", img: "cukn.jpg", keywords: ["浪漫", "魅力", "追求"], upright: "浪漫的追求者。追随心意，魅力四射，追求情感理想。", reversed: "情绪化或失望。可能需要更现实的态度。" },
    { id: 48, name: "圣杯王后", en: "Queen of Cups", numeral: "Q", img: "cuqu.jpg", keywords: ["同情", "直觉", "情感智慧"], upright: "情感智慧和同情心。直觉敏锐，关怀他人，深层理解。", reversed: "情绪依赖或不安全。可能需要建立情感边界。" },
    { id: 49, name: "圣杯国王", en: "King of Cups", numeral: "K", img: "cuki.jpg", keywords: ["情感平衡", "外交", "同情"], upright: "情感的掌控者。情绪平衡，外交手腕，深情稳重。", reversed: "情绪操纵或冷漠。可能需要真实表达情感。" },
    { id: 50, name: "宝剑王牌", en: "Ace of Swords", numeral: "A", img: "sw01.jpg", keywords: ["真理", "清晰", "突破"], upright: "真理和清晰的突破。思维的利剑，斩断困惑，新的想法。", reversed: "困惑或阻滞。可能需要更多反思。" },
    { id: 51, name: "宝剑二", en: "Two of Swords", numeral: "2", img: "sw02.jpg", keywords: ["抉择", "僵局", "否认"], upright: "困难的抉择。信息不足，需要平衡对立，做出决定。", reversed: "真相揭示或情感释放。可能需要面对事实。" },
    { id: 52, name: "宝剑三", en: "Three of Swords", numeral: "3", img: "sw03.jpg", keywords: ["心碎", "悲伤", "痛苦"], upright: "心碎和悲伤。情感痛苦，但这是治愈过程的一部分。", reversed: "恢复或释放痛苦。可能正在走出阴霾。" },
    { id: 53, name: "宝剑四", en: "Four of Swords", numeral: "4", img: "sw04.jpg", keywords: ["休息", "恢复", "冥想"], upright: "休息和恢复。暂停活动，静养恢复，冥想反思。", reversed: "疲惫或停滞。可能需要休息或重新行动。" },
    { id: 54, name: "宝剑五", en: "Five of Swords", numeral: "5", img: "sw05.jpg", keywords: ["冲突", "失败", "背叛"], upright: "冲突和失败。无意义的争斗，损失，需要选择战斗。", reversed: "和解或放下。可能需要结束冲突。" },
    { id: 55, name: "宝剑六", en: "Six of Swords", numeral: "6", img: "sw06.jpg", keywords: ["过渡", "离开", "平静"], upright: "过渡和离开。离开困境，前往更平静的水域。", reversed: "抵抗或被困。可能需要接受转变。" },
    { id: 56, name: "宝剑七", en: "Seven of Swords", numeral: "7", img: "sw07.jpg", keywords: ["欺骗", "策略", "隐秘"], upright: "策略和隐秘行动。可能需要非传统的方法或面临欺骗。", reversed: "真相揭露或忏悔。可能需要诚实。" },
    { id: 57, name: "宝剑八", en: "Eight of Swords", numeral: "8", img: "sw08.jpg", keywords: ["束缚", "恐惧", "受害者"], upright: "束缚和恐惧。自我设限，感到被困，但出路存在。", reversed: "解放或新视角。可能需要认识到限制是自我施加的。" },
    { id: 58, name: "宝剑九", en: "Nine of Swords", numeral: "9", img: "sw09.jpg", keywords: ["焦虑", "噩梦", "恐惧"], upright: "焦虑和恐惧。过度担忧，夜间忧虑，需要理性思考。", reversed: "内心平静或释放恐惧。可能正在走出焦虑。" },
    { id: 59, name: "宝剑十", en: "Ten of Swords", numeral: "10", img: "sw10.jpg", keywords: ["结束", "背叛", "低谷"], upright: "痛苦的结束。谷底已至，但这也意味着新的开始。", reversed: "恢复或抗拒结束。可能正在慢慢恢复。" },
    { id: 60, name: "宝剑侍从", en: "Page of Swords", numeral: "P", img: "swpa.jpg", keywords: ["好奇", "观察", "消息"], upright: "好奇和观察。新想法，寻求真相，消息来临。", reversed: "八卦或狡猾。可能需要更诚实。" },
    { id: 61, name: "宝剑骑士", en: "Knight of Swords", numeral: "K", img: "swkn.jpg", keywords: ["行动", "冲动", "雄心"], upright: "快速行动。追求目标，雄心勃勃，思维敏捷。", reversed: "鲁莽或延迟。可能需要更多计划。" },
    { id: 62, name: "宝剑王后", en: "Queen of Swords", numeral: "Q", img: "swqu.jpg", keywords: ["独立", "清晰", "公正"], upright: "独立和清晰思维。理性分析，直言不讳，公正无私。", reversed: "冷酷或偏见。可能需要更多同情。" },
    { id: 63, name: "宝剑国王", en: "King of Swords", numeral: "K", img: "swki.jpg", keywords: ["智慧", "权威", "真相"], upright: "智慧和权威。理智决策，追求真相，公正领导。", reversed: "操控或冷酷。可能需要更多柔性。" },
    { id: 64, name: "星币王牌", en: "Ace of Pentacles", numeral: "A", img: "pe01.jpg", keywords: ["机遇", "繁荣", "新开始"], upright: "新的物质机遇。财富的开始，实际成功，资源到来。", reversed: "错失机会或财务问题。可能需要更好的规划。" },
    { id: 65, name: "星币二", en: "Two of Pentacles", numeral: "2", img: "pe02.jpg", keywords: ["平衡", "适应", "灵活"], upright: "平衡和多任务处理。灵活适应，管理多个责任。", reversed: "失衡或过度。可能需要简化事务。" },
    { id: 66, name: "星币三", en: "Three of Pentacles", numeral: "3", img: "pe03.jpg", keywords: ["团队合作", "技能", "建设"], upright: "团队合作和建设。与他人协作，提升技能，创造价值。", reversed: "缺乏协作或质量问题。可能需要改进沟通。" },
    { id: 67, name: "星币四", en: "Four of Pentacles", numeral: "4", img: "pe04.jpg", keywords: ["安全", "控制", "保守"], upright: "财务安全和保守。稳定积累，但可能过度执着于物质。", reversed: "慷慨或财务损失。可能需要放下控制。" },
    { id: 68, name: "星币五", en: "Five of Pentacles", numeral: "5", img: "pe05.jpg", keywords: ["困境", "孤立", "缺乏"], upright: "物质困境和孤立。艰难时期，但帮助存在。", reversed: "恢复或精神贫穷。可能正在走出困境。" },
    { id: 69, name: "星币六", en: "Six of Pentacles", numeral: "6", img: "pe06.jpg", keywords: ["慷慨", "分享", "平衡"], upright: "慷慨和分享。给予和接受，财务平衡，慈善行为。", reversed: "自私或债务。可能需要平衡收支。" },
    { id: 70, name: "星币七", en: "Seven of Pentacles", numeral: "7", img: "pe07.jpg", keywords: ["耐心", "评估", "长期"], upright: "耐心和长期投资。努力需要时间，评估进展。", reversed: "不耐烦或缺乏回报。可能需要调整方向。" },
    { id: 71, name: "星币八", en: "Eight of Pentacles", numeral: "8", img: "pe08.jpg", keywords: ["技能", "努力", "熟练"], upright: "勤奋和技能提升。专注工作，精益求精，持续学习。", reversed: "懒惰或缺乏专注。可能需要更多努力。" },
    { id: 72, name: "星币九", en: "Nine of Pentacles", numeral: "9", img: "pe09.jpg", keywords: ["独立", "丰盛", "自足"], upright: "物质丰盛和独立。自给自足，享受成果，财务自由。", reversed: "过度工作或财务依赖。可能需要平衡生活。" },
    { id: 73, name: "星币十", en: "Ten of Pentacles", numeral: "10", img: "pe10.jpg", keywords: ["传承", "家族", "财富"], upright: "家族财富和传承。长期成功，家庭稳固，物质圆满。", reversed: "家庭问题或财务损失。可能需要重新规划。" },
    { id: 74, name: "星币侍从", en: "Page of Pentacles", numeral: "P", img: "pepa.jpg", keywords: ["学习", "机会", "务实"], upright: "学习和新机会。务实态度，开始新的物质旅程。", reversed: "缺乏专注或错失机会。可能需要更多专注。" },
    { id: 75, name: "星币骑士", en: "Knight of Pentacles", numeral: "K", img: "pekn.jpg", keywords: ["勤奋", "可靠", "常规"], upright: "勤奋和可靠。稳步前进，坚守常规，可靠执行。", reversed: "懒惰或固执。可能需要更灵活的态度。" },
    { id: 76, name: "星币王后", en: "Queen of Pentacles", numeral: "Q", img: "pequ.jpg", keywords: ["务实", "养育", "安全"], upright: "务实和滋养。关爱他人，物质安全，实用智慧。", reversed: "过度工作或忽视家庭。可能需要更多自我关爱。" },
    { id: 77, name: "星币国王", en: "King of Pentacles", numeral: "K", img: "peki.jpg", keywords: ["财富", "成功", "商业"], upright: "财富和成功。商业头脑，物质成就，稳健领导。", reversed: "贪婪或物质主义。可能需要更平衡的价值观。" }
];

const SPREAD_POSITIONS = {
    single: [
        { name: "命运之牌", description: "当前情况的核心指引" }
    ],
    three: [
        { name: "过去", description: "影响现在的过去因素" },
        { name: "现在", description: "当前的状况和挑战" },
        { name: "未来", description: "可能的发展方向" }
    ],
    cross: [
        { name: "现状", description: "你现在的处境" },
        { name: "障碍", description: "你面临的挑战" },
        { name: "目标", description: "你希望达到的" },
        { name: "根基", description: "过去的基础影响" },
        { name: "过去", description: "最近的过去影响" },
        { name: "未来", description: "近期的发展" },
        { name: "自我", description: "你的态度和看法" },
        { name: "环境", description: "外界的影响" },
        { name: "希望与恐惧", description: "你的期待与忧虑" },
        { name: "结果", description: "最终的结果" }
    ]
};

const TAROT_IMAGE_BASE = 'https://www.sacred-texts.com/tarot/pkt/img/';
